workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

image: node:lts

stages:
  - lint
  - page

before_script:
  npm install --progress=false

prettier:
  stage: lint
  script:
    - npm run lint
eslint:
  stage: lint
  script:
    - npm run check

pages:
  stage: page
  script:
    - npm run build
  artifacts:
    paths:
      - public

  only:
    - main
