image: node:lts

before_script:
  - npm i

stages:
  - lint
  - page

prettier:
  stage: lint
  script:
    - npm run lint
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
eslint:
  stage: lint
  script:
    - npm run check
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'

pages:
  stage: page
  script:
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
